server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: queueon
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/QueueOn

elasticsearch:
  host: localhost
  port: 9200

management:
  health:
    elasticsearch:
      enabled: true
